### PR TITLE
Don't request SSH verbose output when --log_level=debug

### PR DESCRIPTION
**Pull request by noahl**
PKB's current behavior is to request verbose SSH output (via "ssh -v") whenever --log_level=debug. However, verbose SSH output is *very* verbose. And the problem is frequently not SSH, meaning you have to dig through lots and lots of SSH logs looking for the rare bit of actual PKB debug output to investigate a problem.

This PR adds a --verbose_ssh flag that enables verbose SSH output, and disables
verbose SSH output when --log_level=debug but the verbose_ssh flag is
not set.

I tested by running the fio benchmark with --log_level=debug with and without --verbose_ssh. The output was as expected.

### CODE REVIEW

**Comment by noahl** [comment]
@skschneider @ehankland @yuyantingzero please take a look.

**Comment by skschneider** [comment]
It sounds reasonable to decouple the ssh output (which is present both in stderr and the log file) from the `--log_level` flag, which is tied with values from the python logging system and controls only stderr output. But I see that the `--ssh_options` flag could also be used to enable verbose ssh output, so I suggest omitting the new flag.

**Comment by noahl** [comment]
@skschneider good point. I pushed a new commit without the `--verbose_ssh` flag. PTAL.

**Comment by skschneider** [comment]
LGTM. Make sure to modify the title when merging.

**Comment by noahl** [comment]
@skschneider I changed the title and I'm merging. Thanks.

**Pull request merged**
