### PR TITLE
t3 uses nvme

### PR DESCRIPTION
**Pull request by kczauz**
as per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html

### CODE REVIEW

**Comment by s-deitz** [comment]
Thanks for the update. When you sign the CLA, we'll merge this in.

**Comment by gareth-ferneyhough** [comment]
Ping. Please sign the CLA.

**Comment by kczauz** [comment]
Hi,

The CLA was signed on 8/24/18

**Comment by yuyantingzero** [comment]
LGTM

**Comment by yuyantingzero** [comment]
Please ping us if the change is ready for merging.

**Comment by kczauz** [comment]
It’s ready to merge

**Pull request merged**
