### PR TITLE
add --autodetect option for bq load

### PR DESCRIPTION
**Pull request by DariuszAniszewski**
This PR uses `--autodetect` option (suggested in #1552) to create schema based on uploaded data if table doesn't exists yet. 

It's also seem to be connected to #229. This PR doesn't follow idea from that issue, but final effect is the same - if table doesn't exists, it's being created. Advantage is that it doesn't require additional information and creates schema based on the data.

### CODE REVIEW

**Comment by DariuszAniszewski** [comment]
retest this please

**Comment by DariuszAniszewski** [comment]
@asaksena can you please take a look on this or point some other reviewer? thanks

btw - Is there some problem with test server? Locally running tests are passing without any problems and tests are failing on part far away from the changes.

**Comment by DariuszAniszewski** [comment]
@asaksena can you also take a look on this? Thanks

**Comment by asaksena** [comment]
Darius, I will be testing and closing this PR out this week. Sorry for the delay.

**Comment by DariuszAniszewski** [comment]
Hey @asaksena, any updates on this one? I just merged latest `master` in so changes are up-to-date again.

**Comment by asaksena** [comment]
Merged.

**Comment by DariuszAniszewski** [comment]
Great, thanks!

**Pull request merged**
