### PR TITLE
Fix bug with run stages

### PR DESCRIPTION
**Pull request by ehankland**

### CODE REVIEW

**Comment by skschneider** [comment]
LGTM

**Comment by noahl** [comment]
Does this bug affect release 0.24.0 as well as master?

**Comment by ehankland** [comment]
This affects anything with https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/652 - I don't think it's in 0.24.0 based on the change log, but I could be wrong

**Comment by noahl** [comment]
It's not in 0.24.0. Thanks.

**Pull request merged**
