### PR TITLE
Fix aws on windows

### PR DESCRIPTION
**Pull request by ehankland**
The AWS CLI does not correctly set either $LastExitCode or $? when it
fails (at least with version 1.7.28 which was what I was running with on Windows). 
This leads to us thinking a command succeeded when it didn't.
By adding the option to retry the command in IssueRetryableCommand when
there is output on stderr, we can work around this.

### CODE REVIEW

**Comment by ehankland** [comment]
test this please.

**Comment by ehankland** [comment]
test this please.

**Comment by cmccoy** [comment]
If this is only applicable to `aws`, maybe add a function to `perfkitbenchmarker.aws.util` rather than add more options to IssueRetryableCommand?

**Comment by ehankland** [comment]
Added an aws.util.IssueRetryableCommand function and removed modifications to vm_util.IssueRetryableCommand

PTAL

**Comment by ehankland** [comment]
test this please.

**Comment by cmccoy** [comment]
LGTM.

**Pull request merged**
