### PR TITLE
update version of nova API

### PR DESCRIPTION
**Pull request by kivio**
Update from deprecated version 1.1 to version  2 witch is currently proposed to use.

### CODE REVIEW

**Comment by voellm** [comment]
LGTM... please just double check.cluster_boot and iperf work.  For changes like this those usually catch and issues.

**Comment by kivio** [comment]
@voellm i was checking it!

**Comment by voellm** [comment]
Cool... please let me know when to hit merge.

Optionally Mateusz from Intel and Carlos from Rackspace can now also
complete merges.

**Comment by kivio** [comment]
@voellm i think it can be merged now :) thx :)

**Pull request merged**
