### PR TITLE
Netperf: specify confidence intervals, parse CSV output.

### PR DESCRIPTION
**Pull request by cmccoy**
* Specify confidence intervals and min/max iterations to `netperf`.
* Use and parse CSV output format in place of free text + regex parsing.
* Add confidence width to sample metadata.

### CODE REVIEW

**Comment by cmccoy** [comment]
test this please.

**Comment by voellm** [comment]
Is this dead?  If so please close it otherwise what is the next step?

**Comment by cmccoy** [comment]
test this please.

**Comment by cmccoy** [comment]
This is good to merge. It does change netperf behavior, however:

By explicitly setting a confidence interval and maximum number of iterations to run to achieve that interval, results should be more consistent, but take longer to acquire.  I've seeing a runtime increase of ~3x.  I think that's the right thing to do - the confidence is exposed as 'conf_pct'.

**Comment by voellm** [comment]
The change should be under a flag then.

On Tue, Apr 21, 2015 at 4:23 PM, Connor McCoy <notifications@github.com>
wrote:

> This is good to merge. It does change netperf behavior, however:
>
> By explicitly setting a confidence interval and maximum number of
> iterations to run to achieve that interval, results should be more
> consistent, but take longer to acquire. I've seeing a runtime increase of
> ~3x. I think that's the right thing to do - the confidence is exposed as
> 'conf_pct'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/29#issuecomment-94971727>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by cmccoy** [comment]
I'm going to split this into a pair of PRs.

**Pull request closed without merging**
