### PR TITLE
Remove duplicate requirements files

### PR DESCRIPTION
**Pull request by noahl**
Provider-specific requirements files were moved to provider-specific
directories, but there were still copies in the top-level
directory. Remove those copies.

### CODE REVIEW

**Comment by noahl** [comment]
@skschneider please take a look.

**Comment by noahl** [comment]
@hildrum PTAL.

**Comment by skschneider** [comment]
Conceptually LGTM, but I suggest not merging this until after the v1.5 release, and then have it go into effect in v1.6.

**Comment by noahl** [comment]
@skschneider sounds good to me. I'll wait on this one.

**Comment by hildrum** [comment]
LGTM.  I agree with waiting until after v1.5, so I set it to a v1.6.0 milestone so we don't forget it.

**Comment by hildrum** [comment]
Should we pull this in now?

**Comment by noahl** [comment]
Yes, I think we should go ahead and pull it in. Thanks for remembering this.

**Pull request merged**
