### PR TITLE
Allow newer versions of OpenStack

### PR DESCRIPTION
**Pull request by charliejllewellyn**
The version of the openstack client that is pinned here breaks when running against our cloud. We should allow newer versions which have many bug fixes applied.

### CODE REVIEW

**Comment by charliejllewellyn** [comment]
I signed it!

**Comment by meteorfox** [comment]
Looks good. Which OpenStack release did you test this against? As long as it works with the 'Maintained' releases, in this case Newton, should be OK. My general advice is that If there are breaking changes between two versions, we should try to accommodate both until the old one goes into EOL.

**Comment by charliejllewellyn** [comment]
Hey, this has been run against Mitaka and Newton

**Comment by gareth-ferneyhough** [comment]
Carlons, is this still good with you since it works with Newton?

**Pull request merged**
