### PR TITLE
Aws stripe disks fix

### PR DESCRIPTION
**Pull request by florinpapa**
Fixes https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/1905, based on an initial implementation from @HarpPDX.

Right now, the AWS stripe disks feature wrongly assumes that the boot drive is always at nvme index 0, while in reality the boot drive index can be at any nvme index. This diff fixes that assumption and also adds support for Clear Linux.

### CODE REVIEW

**Comment by s-deitz** [comment]
Thanks for the fix.

There are conflicts in this PR. If you are able to resolve those conflicts, we can merge this change.

**Comment by florinpapa** [comment]
@s-deitz I have rebased with master. Hope everything works now.

**Comment by s-deitz** [comment]
Thanks. That worked and I have merged these changes.

**Comment by florinpapa** [comment]
Thanks @s-deitz. Appreciate the quick response.

**Pull request merged**
