### PR TITLE
added support for custom format for dynamicPipelineOptions

### PR DESCRIPTION
**Pull request by DariuszAniszewski**
this PR solves #1555. It allows PerfKit to return dynamic pipeline option with custom, user-defined format.

### CODE REVIEW

**Comment by szewi** [comment]
Hi, we need this to create complex pipeline options in nice way using PerfKit. This change doesn't brake anything just adds new functionality to beam pipelineoptions parser. 
Example of usage could be seen in `pkb-config.yml` file in [#4401](https://github.com/apache/beam/pull/4401). 
@asaksena @jasonkuster could you help us with that ?

**Comment by asaksena** [comment]
https://travis-ci.org/GoogleCloudPlatform/PerfKitBenchmarker/jobs/328084429 is failing, can you please fix this after which I can merge.

**Comment by DariuszAniszewski** [comment]
@asaksena I found the problem with builds on Travis. It was dependency problem - `numpy` version wasn't fixed and there was recently a bigger update 1.14. I forced older version (1.13.3) and builds are now passing.

The same story is in my other PR #1554 wich was failing due to same issue. After fixing numpy dependency it's green.

This however seems more critical, as not only tests but other parts of system might fail on this. I'm going to file an issue about `numpy 1.14` support and separate PR for fixing the version until full compatibility is proven.

**Comment by chamikaramj** [comment]
@asaksena appreciate if you can merge this.

**Pull request merged**
