### PR TITLE
Adding SuSE support

### PR DESCRIPTION
**Pull request by milkotodorov**

### CODE REVIEW

**Comment by milkotodorov** [comment]
"Authorized Signer" in clarification...

**Comment by voellm** [comment]
Milko I doubled checked and SAP has not signed the CLA.  There are two paths - individual and corporate.  Likely you need to ping your Open Source Lawyers for help.  In the meantime I pinged Google legal to see if they have any contacts at SAP that can help you.

**Comment by milkotodorov** [comment]
Thanks Tony. I already wrote an email asking for the name for the “Authorized Signer”.

**Comment by voellm** [comment]
Any update on the CLA?  We are going to start rolling up v1.1 this week.  Thanks!

**Comment by voellm** [comment]
Ping on the CLA.

**Comment by milkotodorov** [comment]
Hi Tony, sorry, I'll pass the "ping" on to the department who is processing this since January. I didn't expected this to be that slow...

**Comment by milkotodorov** [comment]
Hi Tony, the request for signing the CLA is on our legal department. At least seems to be now at the right person (hopefully the final one).

**Comment by milkotodorov** [comment]
Short update: I see that there is ongoing communication between SAP and Google legal department currently, but still the CLA not signed

**Comment by voellm** [comment]
Thanks for the update.... fingers crossed for SAP legal :)

**Comment by milkotodorov** [comment]
Hi Tony, just an update: our legal department notified me that now they are waiting some lawyer from Google to send the CLA for signing. This is taking ages already. Would you like I put you in the thread between SAP and Google legal if this could help speeding up the things?

**Comment by milkotodorov** [comment]
Hi Tony, can you help with your colleagues from the legal department?

**Comment by noahl** [comment]
Hi @milkotodorov, Tony is no longer at Google. Could you please CC me (`nlavine@google.com`) on the thread? I'll follow up. Sorry for the delay.

**Comment by milkotodorov** [comment]
Hi, why the issue is closed? I know it took a long time for the CLA to be signed, but the changes are committed long ago.

**Comment by milkotodorov** [comment]
I got an info that the CLA should be signed in the next few weeks...

**Comment by hildrum** [comment]
@milkotodorov I didn't mean to close this!  I think what happened is that this pull request is to the dev branch, rather than to the master branch.  Yesterday, I deleted the dev branch, since it's been deprecated.  I can't easily reopen, because the dev branch is deleted (and even if I did, the dev branch wasn't the right destination).  

Can you create a new pull request against the master branch?

**Comment by milkotodorov** [comment]
Hi @hildrum,

what does the "Closed with unmerged commits" means? Unfortunately this process took much longer as expected. Currently the ball is on google legal side.

**Comment by hildrum** [comment]
It was basically an accident on my part.

The way we've been making commits for about a year is that people make pull requests into the master branch of PerfKitBenchmarker.  

Before that, people had been making pull requests into the dev branch, and the dev branch was still hanging around but shouldn't be used, so I deleted it.  When I deleted the dev branch, it closed this pull request, because this pull request is into the dev branch and not the master branch.   I can't easily undelete, and even if I could, it wouldn't matter, because we don't accept pull requests into the dev branch any longer.  

When the legal issues are cleared up, you create a pull request from your dev branch into the PerfkitBenchmarker master branch.

**Comment by milkotodorov** [comment]
hi @hildrum,

I've been just yesterday informed that the CCLA has been signed between Google and SAP. How can we proceed further?

**Comment by milkotodorov** [comment]
Hello?...any update? The CCLA between SAP and Google are already signed, but still the CLA here is at state "no". Would you let me know what must be done more?

**Comment by tedsta** [comment]
Unfortunately hildrum changed teams recently. I can't reopen this PR. Could you submit a new one into the master branch?

**Pull request closed without merging**
