### PR TITLE
Hadoop on Azure

### PR DESCRIPTION
**Pull request by ehankland**
Modifies hdfs conf file so that hadoop can run on Azure

### CODE REVIEW

**Comment by cmccoy** [comment]
LGTM.

**Comment by desaiak** [comment]
For the first time iI was able to actually run Terasort on azure sadly it failed with this ..

Full command: /usr/bin/ssh -A -p 22 perfkit@23.96.94.78 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/run_6a11ff72/perfkitbenchmarker_keyfile hadoop-2.5.2/bin/hadoop jar hadoop-2.5.2/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.5.2.jar  teragen 100000000 /teragen
STDOUT: STDERR: Warning: Permanently added '23.96.94.78' (RSA) to the list of known hosts.
java.io.IOException: Output directory /teragen already exists.
	at org.apache.hadoop.examples.terasort.TeraGen.run(TeraGen.java:293)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.examples.terasort.TeraGen.main(TeraGen.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:72)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:145)
	at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by ehankland** [comment]
The thing that sticks out to me is
"Output directory /teragen already exists."
Could you look at more of the logs to see why this might be the case?

**Comment by desaiak** [comment]
I did .. this is the only thing I found, I am rerunning it with the image fix for openJDK #152 .
Will dig more once/if that fails again with the same reason.

**Comment by ehankland** [comment]
Seems like the real culprit is this:
java.io.IOException: java.net.ConnectException: Call From perfkit-80df7612-0/10.32.0.13 to 0.0.0.0:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
I'm looking into it

**Comment by ehankland** [comment]
Not sure why running the jobhistory server is suddenly required (maybe the config change somehow made it necessary), but running it stops the connection refused error from above. Running to verify that there aren't any other bugs.

**Comment by ehankland** [comment]
Looks like it now succeeds end to end - Connor can you PTAL?

**Comment by cmccoy** [comment]
LGTM.

**Comment by cmccoy** [comment]
This seems good for now. Eventually I think we should use the scripts bundled with hadoop to start the cluster  (`start-dfs.sh` and `start-yarn.sh`).

**Pull request merged**
