### PR TITLE
some wording changes

### PR DESCRIPTION
**Pull request by hildrum**
Made a couple of wording changes as discussed in email.

### CODE REVIEW

**Comment by noahl** [comment]
LGTM

**Comment by hildrum** [comment]
I signed it!

**Comment by yangsophia** [comment]
LGTM. Thank you so much Kris!

**Comment by hildrum** [comment]
googlebot, I'm covered by the Google Inc CLA.

**Comment by ehankland** [comment]
> Check your existing CLA data and verify that your email is set on your git commits.

This is probably the issue. Make sure that the email on your github account is your google one and that it's getting set correctly in the commits.

**Pull request merged**
