### PR TITLE
Add cloudsuite media streaming benchmark

### PR DESCRIPTION
**Pull request by ivonindza**

### CODE REVIEW

**Comment by hildrum** [comment]
jenkins test this please

**Comment by ivonindza** [comment]
clarify please

**Comment by hildrum** [comment]
We have a bot that is supposed to trigger some additional tests when someone enters a comment on a pull request that is "jenkins test this please."  For some reason, it didn't get triggered.  That's okay, because I realized after my comment that the tests wouldn't cover the new code anyway.

**Comment by hildrum** [comment]
LGTM.  Let me know when you want me to pull it in.

**Comment by ivonindza** [comment]
You can pull it in. Thanks.

**Pull request merged**
