### PR TITLE
Enable trim during format and mount.

### PR DESCRIPTION
**Pull request by yuyantingzero**

### CODE REVIEW

**Comment by yuyantingzero** [comment]
Should I enable discard for rackspace machines as well? @voellm @ehankland

**Comment by meteorfox** [comment]
@yuyantingzero feel free to add `discard`. The reason the method are overridden (Format, Mount) is to handle the case where we use a directory in the boot partition as the scratch disk or data disk for a benchmark. Looking at it now, though, this has to be revised.

**Comment by meteorfox** [comment]
@yuyantingzero What's the effect enabling `discard` on an HDD? Is it NOOP?

**Comment by yuyantingzero** [comment]
@meteorfox , trim will be ignored on HDD.

**Comment by voellm** [comment]
@yuyantingzero Please post performance comparative performance numbers and then we can LGTM.  Thanks.

**Comment by voellm** [comment]
@mateusz-blaszkowski @kivio  - Any concerns on your part?

**Comment by mateusz-blaszkowski** [comment]
@voellm I'm OK with the change

**Comment by meteorfox** [comment]
@yuyantingzero @voellm I'm not sure if this was waiting for my reply, but just in case, I'm also OK with the change.

**Comment by voellm** [comment]
Time to merge.

**Pull request merged**
