### PR TITLE
Setting internal ip to pod ip.

### LINKED ISSUE #2044: PodIP address is not populated while running iperf on Kubernetes
Referencing #1990. Sorry for late reply. Even after using ```--ip_addresses=INTERNAL```, IP is not getting populated.
I tried all the options for ```ip_addresses``` -> BOTH, INTERNAL, EXTERNAL, REACHABLE. All give the same issue.
Command used: ```./pkb.py --cloud=Kubernetes --benchmarks=iperf --kubeconfig=/root/.kube/config --image=ptest:v0.2  --ip_addresses=INTERNAL```
Notice: ```root@None``` in below logs

```
Running: ssh -A -p 22 root@None -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp/perfkitbenchmarker/runs/f86259b8/perfkitbenchmarker_keyfile mkdir -p /tmp/pkb```


```

            }
        ],
        "hostIP": "91.106.194.55",
        "phase": "Running",
        "podIP": "10.233.84.192",
        "qosClass": "BestEffort",
        "startTime": "2019-11-20T05:57:07Z"
    }
}
```

### PR DESCRIPTION
**Pull request by msidana**
Fixes #2044

### CODE REVIEW

**Comment by msidana** [comment]
@googlebot I signed it!

**Comment by marcomicera** [comment]
I also had the same problem. This fix solved it.

**Comment by msidana** [comment]
> I also had the same problem. This fix solved it.

This fix will only work when we are running perfkit from within the K8s cluster (since perfkit does SSH via CNI IP).
I am exploring ways to execute perfkit from a VM that is outside my K8s cluster.

**Comment by msidana** [comment]
@marcomicera After this fix, I am also facing issue with SSH. The dockerfile provided in this repo doesn't works. Did you do any modifications in your Dockerfile for running this. I'd be glad if you can share.

**Comment by msidana** [comment]
@jerlawson Can you please take a look at this PR and approve it.

**Comment by shyamsabhaya** [comment]
Please rebase from head so we can see a cleaner diff.

**Comment by msidana** [comment]
> Please rebase from head so we can see a cleaner diff.

Done

**Pull request merged**
