### PR TITLE
add Intel benchmark set and edit README.md

### PR DESCRIPTION
**Pull request by hungvelo**
Please test this out and merge if it works. Thanks.

### CODE REVIEW

**Comment by voellm** [comment]
ok to test

**Comment by voellm** [comment]
test this please

**Comment by voellm** [comment]
Thanks for making the change and fixing comments.  Once the tests pass I'll merge the CL. 

For the next change can you please do it in the Dev branch off master in your fork.  This should allow the pull to go into Dev vs master.  To set the branch on your repo just run "git checkout dev" (http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)

Going into master requires more extensive tests and an update on the version tag.  Dev merges are simpler and then we pick everything up in an ~weekly release and do the bigger tests.

**Comment by voellm** [comment]
Looked into the errors and its a resource limit on CPUs that prevented some tests from running.  The integration tests did all pass on 2 platforms so thats a pass.

**Comment by voellm** [comment]
LGTM

**Comment by hungvelo** [comment]
Hi,
I created a fork off of the dev branch. I just checked the network and it
also showed intel-branch was forked off from the dev branch, not from the
master: https://github.com/hungvelo/PerfKitBenchmarker/network
I followed the instruction on your slides. Did I miss something?

1.Start on GitHub and create a *fork *off of the project.  This will remain
private unit the top level project is public.
2.From your new repository clone the code using the steps on the prior slide
3.Start from dev in your fork (git checkout dev).
4.Create a branch for your changes (git checkout -b <your-branch-name>).
5.Make your modifications to the code in one or more commits (*guidelines
for useful git commit messages
<http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html>*).
6.Push your changes to GitHub (git push origin)
7.Create a pull-request to integrate your change into dev. This can be done
on github.com, or by installing and using the command line tool *gh
<https://github.com/jingweno/gh>* (gh pull-request -h <your-branch-name> -b
dev).

Please let me know if these instructions are correct.
Thank you.

**Comment by cmccoy** [comment]
Hi Hung, 

Thanks for this update! We could have been more clear here - when creating the pull request, the base branch in the comparison should be `dev` (it defaults to master).  I'll update the guidelines.

Connor

**Comment by voellm** [comment]
Ditto to Connors comment.  Sorry for not being more clear.  We'll be
updating a Contributing.md file with instructions.

The good new is the commit is complete and master is now labeled at v0.10.1

On Tue, Feb 24, 2015 at 8:05 AM, Connor McCoy <notifications@github.com>
wrote:

> Hi Hung,
>
> Thanks for this update! We could have been more clear here - when creating
> the pull request, the base branch in the comparison should be dev (it
> defaults to master). I'll update the guidelines.
>
> Connor
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/128#issuecomment-75784948>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Pull request merged**
