### PR TITLE
Expose VM count and scratch disk requirements in help.

### PR DESCRIPTION
**Pull request by cmccoy**
```
Benchmarks:
	aerospike: Runs Aerospike (2 VMs)
	block_storage_workload: Runs FIO in sequential, random, read and write modes to simulate various scenarios. (1 VMs with scratch volume)
	bonnie++: Runs Bonnie++. (1 VMs with scratch volume)
	cassandra_stress: Benchmark Cassandra using cassandra-stress (4 VMs)
	cluster_boot: Create a cluster, record all times to boot (1 VMs)
	copy_throughput: Get cp and scp performance between vms. (1 VMs with scratch volume)
	coremark: Run Coremark a simple processor benchmark (1 VMs)
	fio: Runs fio in sequential, random, read and write modes. (1 VMs with scratch volume)
	hadoop_terasort: Runs Terasort (9 VMs with scratch volume)
	hpcc: Runs HPCC. (1 VMs)
	iperf: Run iperf (2 VMs)
	mesh_network: Measures VM to VM cross section bandwidth in a mesh network. (2 VMs)
	mongodb: Run YCSB against MongoDB. (2 VMs)
	netperf: Run TCP_RR, TCP_CRR, UDP_RR and TCP_STREAM Netperf benchmarks (2 VMs)
	object_storage_service: Object/blob storage service benchmarks. Specify --object_storage_scenario to select a set of sub-benchmarks to run. default is all. (1 VMs with scratch volume)
	oldisim: Run oldisim (6 VMs)
	ping: Benchmarks ping latency over internal IP addresses (2 VMs)
	redis: Run memtier_benchmark against Redis. (6 VMs)
	silo: Runs Silo (1 VMs)
	speccpu2006: Run Spec CPU2006 (1 VMs with scratch volume)
	sysbench_oltp: Runs Sysbench OLTP (1 VMs with scratch volume)
	unixbench: Runs UnixBench. (1 VMs with scratch volume)
```

### CODE REVIEW

**Comment by cmccoy** [comment]
See #240

**Comment by voellm** [comment]
LGTM

**Comment by cmccoy** [comment]
For posterity: here is the relevant section of `python pkb.py --help` before the change:
```
Benchmarks:
	aerospike:  Runs Aerospike
	block_storage_workload:  Runs FIO in sequential, random, read and write modes to simulate various scenarios.
	bonnie++:  Runs Bonnie++.
	cassandra_stress:  Benchmark Cassandra using cassandra-stress
	cluster_boot:  Create a cluster, record all times to boot
	copy_throughput:  Get cp and scp performance between vms.
	coremark:  Run Coremark a simple processor benchmark
	fio:  Runs fio in sequential, random, read and write modes.
	hadoop_terasort:  Runs Terasort
	hpcc:  Runs HPCC.
	iperf:  Run iperf
	mesh_network:  Measures VM to VM cross section bandwidth in a mesh network.
	mongodb:  Run YCSB against MongoDB.
	netperf:  Run TCP_RR, TCP_CRR, UDP_RR and TCP_STREAM Netperf benchmarks
	object_storage_service:  Object/blob storage service benchmarks. Specify --object_storage_scenario to select a set of sub-benchmarks to run. default is all.
	oldisim:  Run oldisim
	ping:  Benchmarks ping latency over internal IP addresses
	redis:  Run memtier_benchmark against Redis.
	silo:  Runs Silo
	speccpu2006:  Run Spec CPU2006
	sysbench_oltp:  Runs Sysbench OLTP
	unixbench:  Runs UnixBench.
```

**Comment by cmccoy** [comment]
@ehankland: You're right; I was thinking of the raw `BENCHMARK_INFO`.

We should denote which benchmarks can use a variable number of VMs. What do you think about just adding a sentence to the benchmark docstring? This affects `cluster_boot`, `mesh_network`, `oldisim`, and `redis`.

**Comment by ehankland** [comment]
Sounds good to me

**Comment by cmccoy** [comment]
New list, as of bf2782af7fb8c179343ef6bb7d2cb7a9262da11b:
```
Benchmarks (default requirements):
	aerospike: Runs Aerospike (2 VMs)
	block_storage_workload: Runs FIO in sequential, random, read and write modes to simulate various scenarios. (1 VMs with scratch volume)
	bonnie++: Runs Bonnie++. (1 VMs with scratch volume)
	cassandra_stress: Benchmark Cassandra using cassandra-stress (4 VMs)
	cluster_boot: Create a cluster, record all times to boot. Specify the cluster size with --num_vms. (1 VMs)
	copy_throughput: Get cp and scp performance between vms. (1 VMs with scratch volume)
	coremark: Run Coremark a simple processor benchmark (1 VMs)
	fio: Runs fio in sequential, random, read and write modes. (1 VMs with scratch volume)
	hadoop_terasort: Runs Terasort (9 VMs with scratch volume)
	hpcc: Runs HPCC. Specify the number of VMs with --num_vms (1 VMs)
	iperf: Run iperf (2 VMs)
	mesh_network: Measures VM to VM cross section bandwidth in a mesh network. Specify the number of VMs in the network with --num_vms. (2 VMs)
	mongodb: Run YCSB against MongoDB. (2 VMs)
	netperf: Run TCP_RR, TCP_CRR, UDP_RR and TCP_STREAM Netperf benchmarks (2 VMs)
	object_storage_service: Object/blob storage service benchmarks. Specify --object_storage_scenario to select a set of sub-benchmarks to run. default is all. (1 VMs with scratch volume)
	oldisim: Run oldisim. Specify the number of leaf nodes with --oldisim_num_leaves (6 VMs)
	ping: Benchmarks ping latency over internal IP addresses (2 VMs)
	redis: Run memtier_benchmark against Redis. Specify the number of client VMs with --redis_clients. (6 VMs)
	silo: Runs Silo (1 VMs)
	speccpu2006: Run Spec CPU2006 (1 VMs with scratch volume)
	sysbench_oltp: Runs Sysbench OLTP (1 VMs with scratch volume)
	unixbench: Runs UnixBench. (1 VMs with scratch volume)
```

**Comment by ehankland** [comment]
LGTM

**Comment by cmccoy** [comment]
test this please.

**Comment by hungvelo** [comment]
Nice! Thanks for adding this info. Can we please also add the cpuinfo and the "PerfKitBenchmarker Results Summary" to the pkb.log file? For example, cat /proc/cpuinfo.

**Comment by cmccoy** [comment]
@hungvelo: I just added the results summary in #68. Would you mind opening a bug to include cpuinfo in the log? Thanks!

**Comment by hungvelo** [comment]
@cmccoy: I just opened a new bug, #245

**Pull request merged**
