### PR TITLE
Update comments in Azure CLI tests to confirm it only does sequential op...

### PR DESCRIPTION
**Pull request by stfeng**
...s. Reduce iteration count further to 3.

### CODE REVIEW

**Comment by stfeng** [comment]
@yuyantingzero 

Please take a look.

**Comment by yuyantingzero** [comment]
LGTM

**Comment by voellm** [comment]
Please check in today if you would like it in v0.14.0.  Thanks!

**Comment by stfeng** [comment]
@voellm: Thanks for the reminder! checked-in.

**Pull request merged**
