### PR TITLE
[mysql_service_benchmark] Data loading thread count

### PR DESCRIPTION
**Pull request by sspano**
@stfeng @gareth-ferneyhough 
Update number of threads for data loading to be the smaller number of thread count and table_count. This is because data loading (prepare phase) is write only so we don't want more threads than tables for this phase.

### CODE REVIEW

**Comment by stfeng** [comment]
travis build failed, did you see the same error on your command line when you ran flake8?

**Comment by sspano** [comment]
Absolutely my bad.. forget to run tox... passes now.

**Comment by gareth-ferneyhough** [comment]
LGTM

**Comment by stfeng** [comment]
LGTM, merging...

**Pull request merged**
