### PR TITLE
Azure: remove use of affinity groups.

### PR DESCRIPTION
**Pull request by cmccoy**
Affinity groups [are deprecated](https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-migrate-to-regional-vnet/), replaced by regional virtual networks.

Also switches Endpoints to be PKB resources, which makes creating them a bit more resilient.

### CODE REVIEW

**Comment by ehankland** [comment]
Could you make sure that this doesn't break remote ssd on Azure? I think we rely on affinity groups to make it work, but I could be wrong.

**Comment by cmccoy** [comment]
@ehankland - will do, thanks.

**Comment by ehankland** [comment]
@cmccoy thanks. Specifically, I don't think we specify which storage account to use when creating disks/vms - in the affinity groups we set up there's only one to choose from, but without it I'm not sure what will happen (if there are multiple storage accounts in the same location). I suspect everything will seem to work even if it breaks, but you'll get the wrong disk type.

**Comment by hildrum** [comment]
Has the status of this changed?

**Comment by cmccoy** [comment]
No, I haven't looked more.

**Comment by voellm** [comment]
@ehankland - Can you work with Connor to complete this.  Thanks!

**Comment by cmccoy** [comment]
#833 has a superset of these features, so I'll close this in favor of that PR.

**Pull request closed without merging**
