### PR TITLE
Azure: defer endpoint creation until after VM creation.

### PR DESCRIPTION
**Pull request by cmccoy**

### CODE REVIEW

**Comment by cmccoy** [comment]
@skschneider / @ehankland - could you take a look?

**Comment by skschneider** [comment]
LGTM.
The lock is probably unnecessary.

**Comment by skschneider** [comment]
Checked test errors, and they're caused by #723. Okay to merge.

**Comment by skschneider** [comment]
test this please

**Comment by skschneider** [comment]
test this please.

**Comment by ehankland** [comment]
Looks like the AWS firewall depends on the VM's group id:
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/providers/aws/aws_network.py#L67

**Pull request closed without merging**
