### PR TITLE
Add RHEL based virtual machines to OpenStack provider.

### PR DESCRIPTION
**Pull request by akrzos**
Allow RHEL based virtual machines to be benchmarked on OpenStack provider.

### CODE REVIEW

**Comment by akrzos** [comment]
My company (Red Hat) should have signed the CLA already.

**Comment by akrzos** [comment]
I signed it!

**Comment by voellm** [comment]
LGTM

@ehankland  - If you agree on the LGTM I'll complete the pull request.

**Comment by ehankland** [comment]
LGTM

**Pull request merged**
