### PR TITLE
Add a Juju cloud provider + benchmark

### PR DESCRIPTION
**Pull request by AdamIsrael**
This pull request adds support for Juju as a cloud, as well as the ability to run juju benchmarks via perfkit.

### CODE REVIEW

**Comment by voellm** [comment]
Super cool to see this coming in... Eric is going to help with the integration.

**Comment by voellm** [comment]
Adam - Couple of questions and changes for this CL.

1. In the "Copyright ...." statements please replace "Canonical" with "PerfKitBenchmarker Authors".  We then need to add an AUTHORS file in the root.  In that file we should have "Google Inc., Canonical Inc, Intel Inc., Rackspace Inc.".
2. I'm not sure what the Juju_benchmark_... is for.  Can you explain to expected outcome?  Likely what you want is to have a Juju package manager that when asked to install "mysql" it does it via Juju's vs Apt-get.
3. You asked the question about multiple benchmarks / configs in email.  Check out this how-to - https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/PerfkitBenchmarker-Configurations

Eric will add more feedback on Monday. 

Thanks for the pull request!

**Comment by AdamIsrael** [comment]
The Juju benchmark is intended to be a proxy between perfkit and Juju with regard to which benchmark to run, as specified by `--action` and `--action-params`. For example, `--action=mongodb:perf` tells us to identify the machine running the mongodb charm and execute it's `perf` action. Similar actions can be executed against mysql, hadoop, etc.

All of the benchmarks parse and return the data in a standard format, which the Juju benchmark reformats to work with perfkit.

Thanks for the link wrt multiple benchmarks/configs. We wanted to avoid having to add new flags, if possible, and were hoping to reuse `--benchmarks` so that something like `--cloud=juju --benchmarks=mongodb:perf` would do the right thing. I'll read through that doc, update the copyright and update the pull request shortly.

**Comment by voellm** [comment]
Thanks for the explanation.  The thing I'd like to see here is not a second
benchmarking system added to PKB.  That's what this looks like.  What I'd
like to do is have Charms/Juju act like every other Cloud provider and use
the existing benchmarks as is -and- just take over the provisions of the
software used.  This means --benchmarks=mongodb would just work.

So the refactor is to remove the juju benchmark and take over the package
install.





On Mon, Oct 26, 2015 at 12:39 PM, Adam Israel <notifications@github.com>
wrote:

> The Juju benchmark is intended to be a proxy between perfkit and Juju with
> regard to which benchmark to run, as specified by --action and
> --action-params. For example, --action=mongodb:perf tells us to identify
> the machine running the mongodb charm and execute it's perf action.
> Similar actions can be executed against mysql, hadoop, etc.
>
> All of the benchmarks parse and return the data in a standard format,
> which the Juju benchmark reformats to work with perfkit.
>
> Thanks for the link wrt multiple benchmarks/configs. We wanted to avoid
> having to add new flags, if possible, and were hoping to reuse
> --benchmarks so that something like --cloud=juju --benchmarks=mongodb:perf
> would do the right thing. I'll read through that doc, update the copyright
> and update the pull request shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/582#issuecomment-151260968>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Comment by AdamIsrael** [comment]
Hey Tony,

Thanks for the feedback! We're going to close this PR and start iterating on your feedback. We'll resubmit in a week or so when we're ready to have you take another look.

Thanks again!

**Comment by voellm** [comment]
No problem.  Happy to video chat and walk though integration if that helps.
 @ehankland can also be a good person for questions.

On Fri, Oct 30, 2015 at 2:15 PM, Adam Israel <notifications@github.com>
wrote:

> Hey Tony,
>
> Thanks for the feedback! We're going to close this PR and start iterating
> on your feedback. We'll resubmit in a week or so when we're ready to have
> you take another look.
>
> Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/582#issuecomment-152653168>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/
Benchmark like a pro... PerfKitBenchmarker
<https://github.com/GoogleCloudPlatform/PerfKitBenchmarker>

**Pull request closed without merging**
