### PR TITLE
Update go language binary to version 1.17.2

### PR DESCRIPTION
**Pull request by Nowasky**
Go client libraries from cloud.google.com/go may require an updated Go version. For instance, github.com/google/go-github requires Go version 1.13 or greater.

### CODE REVIEW

**Comment by yuyantingzero** [comment]
@bvliu any comments?

**Review by bvliu — APPROVED** [review]

**Comment by bvliu** [comment]
Seems to be some merge conflict here, can you resolve them so the branch can be rebased? Thanks.

**Comment by Nowasky** [comment]
Can you try to rebase again? Thanks

**Review by bvliu — APPROVED** [review]

**Comment by Nowasky** [comment]
When is this going to be merged?

**Comment by bvliu** [comment]
Hmm looks like this did not make it in as expected, looking.

**Comment by bvliu** [comment]
Apologies, looks like our import pipeline was having issues. Could you resolve merge conflicts a final time and I will get this in today? Thanks!

**Comment by bvliu** [comment]
Actually, let me see if I can resolve on my side.

**Comment by bvliu** [comment]
Thanks for your patience and the ping to get this in.

**Pull request merged**
