### PR TITLE
Made changes so that kubectl reads from file instead of piping

### PR DESCRIPTION
**Pull request by nehayward**

### CODE REVIEW

**Comment by nehayward** [comment]
I signed it!

**Comment by hildrum** [comment]
I see you have signed it; I'm not sure why the CLAbot didn't see that.  You might try a "I signed it!" again, but it looks like you also have some flake errors that need to be fixed.

**Comment by tedsta** [comment]
There are some linter errors. Could you run `hooks/check-everything` and fix the errors you get?

**Comment by nehayward** [comment]
Yes I'll make those changes

**Pull request closed without merging**
