### PR TITLE
Fix bug #911 to update redis package

### PR DESCRIPTION
**Pull request by mlpesant**
perfkitbenchmarker/linux_packages/redis_server.py was hardcoded to pull version 2.8.9 of redis. Updated this to pull the latest stable version from the redis release website.

### CODE REVIEW

**Comment by mlpesant** [comment]
@voellm How can I fix this CLA issue?  I added both my email addresses to my github profile.  Thanks!

**Comment by voellm** [comment]
Best to remove the non-IBM account.  IBM has signed the CLA  but if there
is an account without the CLA the bot blocks the integration.  Optionally
you could sign the CLA with the other account.

**Comment by mlpesant** [comment]
I signed it

**Comment by mlpesant** [comment]
@voellm, how can I get some assistance with the CLA issues?  I tried adding my ibm email address as an alternate email address to my Google account, and I also added my google address to my github account but this didn't help.  Neither will let me change the primary email address.

**Comment by voellm** [comment]
I set it manually.  Can you resolve the conflicts and then we can integrate it.  Thanks.

**Comment by mlpesant** [comment]
Thanks!  Done.

**Comment by voellm** [comment]
test this please.

**Comment by voellm** [comment]
Look like the branch is still out of sync.   Ive kicked off some
integration tests.

**Comment by stfeng** [comment]
FYI - The cut-off date for the next release is EOD Thursday 3/31.

**Comment by hildrum** [comment]
Do you need some help merging this?  It looks like if you rebase and drop the commits that don't have to do with your work, then there will be no conflicts, and it would get rid of the CLA issue.  

That is:
  1.  `git remote add upstream git@github.com:GoogleCloudPlatform/PerfKitBenchmarker.git -t master`  
  1. `git fetch upstream master` (not sure this one is needed)
  1.  `git rebase -i upstream/master` This will bring up an editor; choose drop for the first two commits that have nothing to do with your work.

**Comment by s-deitz** [comment]
This PR is over a year old and it looks like we lost track of it. Is this still valid? If so, please reply and somebody will review in the next couple of weeks.

**Pull request closed without merging**
