### PR TITLE
Enable OCI as a Cloud provider in PKB. 

### PR DESCRIPTION
**Pull request by gadgilrajeev**
Enable OCI as a cloud provider in PKB

- Virtual Machines:

  - Launch Shapes. Currently supports only Flex VM​
  - What can you configure​   
  - Image (Either Ubuntu or Oracle)​
  - Size of Boot Disk (currently only supports Paravirtualized Boot disk)​
  - Machine always gets assigned an external ip address (no option to disable this)​
  - ssh-key pair for every transaction is different autogenerated. Does not yet support providing userdefined ssh-keys​
  - Username is always "perfkit". (No option to change this)​
  - Iptables are flushed on boot in Ubuntu images and firewalld service are disabled in Oracle Linux images (Cloud-init). This ensures we do not need to deal with individual firewall rules​. Will be implemented in NSG
  - Freeform Tags are automatically added 

- OCI Network:
  - oci_use_vcn: (equivalency to gce_use_vcn)  ​
    -   False: Can use Preconfigured network​
    -   True: PKB will manage creating VCN, subnet, Internet Gateway and Security Rules​
  - CIDR block is always created with 17.16.0.0/16​
  - Security Rules on local subnet (172.16.0.0) is ingress all ports open. Only port 22 is open on external ip.

- OCI Block Volume (BV)​ <-> Disks
  - Supports following types of block volumes (not boot volumes)​
    - Paravirtualized​
    - iscsi​
  - Size of disks is settable. ​
  - Multiple disks can be attached to a shape. Upto 32 disks can be attached. 
  - vpus: option in YAML to define the disk with a given IOPS that will  be launched. ​
    - Acceptable values for vpus per GB is​
      - 0: Represents Lower Cost option.​
      - 10: Represents Balanced option.​
      - 20: Represents Higher Performance option.​
  - Attaching disks is handled automatically. iscsi attach commands are also autogenerated and executed.​
  - Boot volume disk type is always paravirtualized

Oracle 8 and Oracle 9 Linux related changes will be pushed in a separate commit.

What is not supported:

1. Opening specific ports in the firewall. Eg: iperf​
2. Network security Group management – WIP​
3. VNICs cannot be placed in NSG and attached to a Shape​
4. Launching Clusters is not supported as of now​
5. Launching user provided boot images is not supported​
6. Launching OCI services (Eg: OracleDB, mysql as a service) is not supported.​

#### Need account on OCI and OCI CLI tools installed:

- Create a virtual environment​
- Enable a virtual Environment source ./venv/bin/activate​
- Install OCI CLI​ https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm​
- For MacOS​ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

Example PKB log attached with memcached-memtier

[pkb.log](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/files/10839892/pkb.log)

### CODE REVIEW

**Comment by s-deitz** [comment]
Thanks for the potential contribution. We are discussing this PR and will try to get back to you in the next two weeks with more information.

**Comment by gadgilrajeev** [comment]
Any update?

**Comment by s-deitz** [comment]
Hi Rajeev

Thanks for your patience. We can accept this as a contribution, but will only do a light review and won't run or test the contribution. There is a risk that we may break this with changes so will appreciate further contributions from you or the community.

@asaksena Please find someone to light review and pull in.

**Comment by gadgilrajeev** [comment]
@s-deitz @asaksena any possibility to follow up on this?

**Comment by anksena** [comment]
Hi Rajeev, 

First I apologize for the delay.
May I kindly request you to remove the following folders from the PR

bash_scripts/*
config_files/*
docs/*

I do not see them being related to the OCI
Please correct me if I am wrong.

thanks

**Comment by gadgilrajeev** [comment]
I am going to close this pull request and open a new one. There is too much conflict in the current codebase.

**Comment by gadgilrajeev** [comment]
Moving to a new pull request.

**Pull request closed without merging**
